spring:
  #プロファイル名(変更する場合はファイル名のハイフン以下も変更してください)
  profiles: postgres-local

  #postgreSQL接続設定
  datasource:
     #ドライバー名
     driver-class-name: org.postgresql.Driver
     #接続URL
     url:  jdbc:postgresql://localhost:5432/spring_office_employee
     #DBユーザー名
     username: postgres
     #DBパスワード
     password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com #change email id
    password: password # insert password
    protocol: smtp
    properties.mail.smtp:
             auth: true
             starttls.enable: true
             ssl.trust: smtp.gmail.com
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false
