CREATE TABLE IF NOT EXISTS cards_retain (
        PERIOD_MONTH DATE,
        EMPLOYEE_ID VARCHAR(6) NOT NULL,
        EMPCARD_OWNER CHAR(1),
        CARD1_NM VARCHAR(50),
        CARD2_NM VARCHAR(50),
        CARD3_NM VARCHAR(50),
        CARD4_NM VARCHAR(50),
        CARD5_NM VARCHAR(50),
        CARD6_NM VARCHAR(50),
        CARD7_NM VARCHAR(50),
        CREATE_USER VARCHAR(6),
        CREATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREATE_PGID VARCHAR(15),
        UPDATE_USER VARCHAR(6),
        UPDATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATE_PGID VARCHAR(15),
        PRIMARY KEY(PERIOD_MONTH, EMPLOYEE_ID)
);