CREATE TABLE IF NOT EXISTS MENUS(
       MENU_ID SERIAL,
       MENU_NAME VARCHAR(100),
       DESCRIPTION VARCHAR(255),
       CREATE_USER VARCHAR(6),
       CREATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREATE_PGID VARCHAR(6),
       UPDATE_USER VARCHAR(6),
       UPDATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
       UPDATE_PGID VARCHAR(6)
);
CREATE SEQUENCE SEQ_MENU_ID AS INTEGER START 1 OWNED BY MENUS.MENU_ID;


CREATE TABLE IF NOT EXISTS ROLES(
        ROLE_ID SERIAL,
        ROLE_NAME VARCHAR(100),
        DESCRIPTION VARCHAR(255),
        CREATE_USER VARCHAR(6),
        CREATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREATE_PGID VARCHAR(6),
        UPDATE_USER VARCHAR(6),
        UPDATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATE_PGID VARCHAR(6)
);
CREATE SEQUENCE SEQ_ROLE_ID AS INTEGER START 1 OWNED BY ROLES.ROLE_ID;

CREATE TABLE IF NOT EXISTS ROLE_MENU_PERMISSIONS (
        ROLE_MENU_PERMISSION_ID SERIAL,
        MENU_ID INTEGER NOT NULL,
        ROLE_ID INTEGER NOT NULL,
        CREATE_USER VARCHAR(6),
        CREATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREATE_PGID VARCHAR(6),
        UPDATE_USER VARCHAR(6),
        UPDATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATE_PGID VARCHAR(6)
);

CREATE SEQUENCE SEQ_ROLE_MENU_PERMISSION_ID AS integer START 1 OWNED BY ROLE_MENU_PERMISSIONS.ROLE_MENU_PERMISSION_ID;

CREATE TABLE IF NOT EXISTS JOB_POSTS (
        post_code VARCHAR(4) PRIMARY KEY NOT NULL,
        post_name TEXT NOT NULL,
        create_user VARCHAR(6) NOT NULL,
        create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        create_pgid VARCHAR(15) NOT NULL,
        update_user VARCHAR(6) NOT NULL,
        update_date TIMESTAMP WITH TIME ZONE NOT NULL,
        update_pgid VARCHAR(15) NOT NULL
);



CREATE TABLE IF NOT EXISTS DEPARTMENTS (
       dept_code VARCHAR(6) PRIMARY KEY NOT NULL,
       dept_name VARCHAR(30),
       create_user VARCHAR(6) NOT NULL,
       create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
       create_pgid VARCHAR(15) NOT NULL,
       update_user VARCHAR(6) NOT NULL,
       update_date TIMESTAMP WITH TIME ZONE NOT NULL,
       update_pgid VARCHAR(15) NOT NULL
);
