CREATE TABLE IF NOT EXISTS close_status (
       CLOSE_DATE DATE PRIMARY KEY NOT NULL,
       CLOSE_FLAG INTEGER NOT NULL,
       CREATE_USER VARCHAR(6),
       CREATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREATE_PGID VARCHAR(15),
       UPDATE_USER VARCHAR(6),
       UPDATE_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
       UPDATE_PGID VARCHAR(15)
);