package sp.co.soe.emp.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CardsRetainExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public CardsRetainExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andPeriodMonthIsNull() {
			addCriterion("period_month is null");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthIsNotNull() {
			addCriterion("period_month is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthEqualTo(Date value) {
			addCriterionForJDBCDate("period_month =", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthNotEqualTo(Date value) {
			addCriterionForJDBCDate("period_month <>", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthGreaterThan(Date value) {
			addCriterionForJDBCDate("period_month >", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("period_month >=", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthLessThan(Date value) {
			addCriterionForJDBCDate("period_month <", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("period_month <=", value, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthIn(List<Date> values) {
			addCriterionForJDBCDate("period_month in", values, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthNotIn(List<Date> values) {
			addCriterionForJDBCDate("period_month not in", values, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("period_month between", value1, value2, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andPeriodMonthNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("period_month not between", value1, value2, "periodMonth");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("employee_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(String value) {
			addCriterion("employee_id =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(String value) {
			addCriterion("employee_id <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(String value) {
			addCriterion("employee_id >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(String value) {
			addCriterion("employee_id >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(String value) {
			addCriterion("employee_id <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(String value) {
			addCriterion("employee_id <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLike(String value) {
			addCriterion("employee_id like", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotLike(String value) {
			addCriterion("employee_id not like", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<String> values) {
			addCriterion("employee_id in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<String> values) {
			addCriterion("employee_id not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(String value1, String value2) {
			addCriterion("employee_id between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(String value1, String value2) {
			addCriterion("employee_id not between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerIsNull() {
			addCriterion("empcard_owner is null");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerIsNotNull() {
			addCriterion("empcard_owner is not null");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerEqualTo(String value) {
			addCriterion("empcard_owner =", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerNotEqualTo(String value) {
			addCriterion("empcard_owner <>", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerGreaterThan(String value) {
			addCriterion("empcard_owner >", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerGreaterThanOrEqualTo(String value) {
			addCriterion("empcard_owner >=", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerLessThan(String value) {
			addCriterion("empcard_owner <", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerLessThanOrEqualTo(String value) {
			addCriterion("empcard_owner <=", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerLike(String value) {
			addCriterion("empcard_owner like", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerNotLike(String value) {
			addCriterion("empcard_owner not like", value, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerIn(List<String> values) {
			addCriterion("empcard_owner in", values, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerNotIn(List<String> values) {
			addCriterion("empcard_owner not in", values, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerBetween(String value1, String value2) {
			addCriterion("empcard_owner between", value1, value2, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andEmpcardOwnerNotBetween(String value1, String value2) {
			addCriterion("empcard_owner not between", value1, value2, "empcardOwner");
			return (Criteria) this;
		}

		public Criteria andCard1NmIsNull() {
			addCriterion("card1_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard1NmIsNotNull() {
			addCriterion("card1_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard1NmEqualTo(String value) {
			addCriterion("card1_nm =", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmNotEqualTo(String value) {
			addCriterion("card1_nm <>", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmGreaterThan(String value) {
			addCriterion("card1_nm >", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmGreaterThanOrEqualTo(String value) {
			addCriterion("card1_nm >=", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmLessThan(String value) {
			addCriterion("card1_nm <", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmLessThanOrEqualTo(String value) {
			addCriterion("card1_nm <=", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmLike(String value) {
			addCriterion("card1_nm like", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmNotLike(String value) {
			addCriterion("card1_nm not like", value, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmIn(List<String> values) {
			addCriterion("card1_nm in", values, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmNotIn(List<String> values) {
			addCriterion("card1_nm not in", values, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmBetween(String value1, String value2) {
			addCriterion("card1_nm between", value1, value2, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard1NmNotBetween(String value1, String value2) {
			addCriterion("card1_nm not between", value1, value2, "card1Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmIsNull() {
			addCriterion("card2_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard2NmIsNotNull() {
			addCriterion("card2_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard2NmEqualTo(String value) {
			addCriterion("card2_nm =", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmNotEqualTo(String value) {
			addCriterion("card2_nm <>", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmGreaterThan(String value) {
			addCriterion("card2_nm >", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmGreaterThanOrEqualTo(String value) {
			addCriterion("card2_nm >=", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmLessThan(String value) {
			addCriterion("card2_nm <", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmLessThanOrEqualTo(String value) {
			addCriterion("card2_nm <=", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmLike(String value) {
			addCriterion("card2_nm like", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmNotLike(String value) {
			addCriterion("card2_nm not like", value, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmIn(List<String> values) {
			addCriterion("card2_nm in", values, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmNotIn(List<String> values) {
			addCriterion("card2_nm not in", values, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmBetween(String value1, String value2) {
			addCriterion("card2_nm between", value1, value2, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard2NmNotBetween(String value1, String value2) {
			addCriterion("card2_nm not between", value1, value2, "card2Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmIsNull() {
			addCriterion("card3_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard3NmIsNotNull() {
			addCriterion("card3_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard3NmEqualTo(String value) {
			addCriterion("card3_nm =", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmNotEqualTo(String value) {
			addCriterion("card3_nm <>", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmGreaterThan(String value) {
			addCriterion("card3_nm >", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmGreaterThanOrEqualTo(String value) {
			addCriterion("card3_nm >=", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmLessThan(String value) {
			addCriterion("card3_nm <", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmLessThanOrEqualTo(String value) {
			addCriterion("card3_nm <=", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmLike(String value) {
			addCriterion("card3_nm like", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmNotLike(String value) {
			addCriterion("card3_nm not like", value, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmIn(List<String> values) {
			addCriterion("card3_nm in", values, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmNotIn(List<String> values) {
			addCriterion("card3_nm not in", values, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmBetween(String value1, String value2) {
			addCriterion("card3_nm between", value1, value2, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard3NmNotBetween(String value1, String value2) {
			addCriterion("card3_nm not between", value1, value2, "card3Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmIsNull() {
			addCriterion("card4_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard4NmIsNotNull() {
			addCriterion("card4_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard4NmEqualTo(String value) {
			addCriterion("card4_nm =", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmNotEqualTo(String value) {
			addCriterion("card4_nm <>", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmGreaterThan(String value) {
			addCriterion("card4_nm >", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmGreaterThanOrEqualTo(String value) {
			addCriterion("card4_nm >=", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmLessThan(String value) {
			addCriterion("card4_nm <", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmLessThanOrEqualTo(String value) {
			addCriterion("card4_nm <=", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmLike(String value) {
			addCriterion("card4_nm like", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmNotLike(String value) {
			addCriterion("card4_nm not like", value, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmIn(List<String> values) {
			addCriterion("card4_nm in", values, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmNotIn(List<String> values) {
			addCriterion("card4_nm not in", values, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmBetween(String value1, String value2) {
			addCriterion("card4_nm between", value1, value2, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard4NmNotBetween(String value1, String value2) {
			addCriterion("card4_nm not between", value1, value2, "card4Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmIsNull() {
			addCriterion("card5_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard5NmIsNotNull() {
			addCriterion("card5_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard5NmEqualTo(String value) {
			addCriterion("card5_nm =", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmNotEqualTo(String value) {
			addCriterion("card5_nm <>", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmGreaterThan(String value) {
			addCriterion("card5_nm >", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmGreaterThanOrEqualTo(String value) {
			addCriterion("card5_nm >=", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmLessThan(String value) {
			addCriterion("card5_nm <", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmLessThanOrEqualTo(String value) {
			addCriterion("card5_nm <=", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmLike(String value) {
			addCriterion("card5_nm like", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmNotLike(String value) {
			addCriterion("card5_nm not like", value, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmIn(List<String> values) {
			addCriterion("card5_nm in", values, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmNotIn(List<String> values) {
			addCriterion("card5_nm not in", values, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmBetween(String value1, String value2) {
			addCriterion("card5_nm between", value1, value2, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard5NmNotBetween(String value1, String value2) {
			addCriterion("card5_nm not between", value1, value2, "card5Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmIsNull() {
			addCriterion("card6_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard6NmIsNotNull() {
			addCriterion("card6_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard6NmEqualTo(String value) {
			addCriterion("card6_nm =", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmNotEqualTo(String value) {
			addCriterion("card6_nm <>", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmGreaterThan(String value) {
			addCriterion("card6_nm >", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmGreaterThanOrEqualTo(String value) {
			addCriterion("card6_nm >=", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmLessThan(String value) {
			addCriterion("card6_nm <", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmLessThanOrEqualTo(String value) {
			addCriterion("card6_nm <=", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmLike(String value) {
			addCriterion("card6_nm like", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmNotLike(String value) {
			addCriterion("card6_nm not like", value, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmIn(List<String> values) {
			addCriterion("card6_nm in", values, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmNotIn(List<String> values) {
			addCriterion("card6_nm not in", values, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmBetween(String value1, String value2) {
			addCriterion("card6_nm between", value1, value2, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard6NmNotBetween(String value1, String value2) {
			addCriterion("card6_nm not between", value1, value2, "card6Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmIsNull() {
			addCriterion("card7_nm is null");
			return (Criteria) this;
		}

		public Criteria andCard7NmIsNotNull() {
			addCriterion("card7_nm is not null");
			return (Criteria) this;
		}

		public Criteria andCard7NmEqualTo(String value) {
			addCriterion("card7_nm =", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmNotEqualTo(String value) {
			addCriterion("card7_nm <>", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmGreaterThan(String value) {
			addCriterion("card7_nm >", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmGreaterThanOrEqualTo(String value) {
			addCriterion("card7_nm >=", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmLessThan(String value) {
			addCriterion("card7_nm <", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmLessThanOrEqualTo(String value) {
			addCriterion("card7_nm <=", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmLike(String value) {
			addCriterion("card7_nm like", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmNotLike(String value) {
			addCriterion("card7_nm not like", value, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmIn(List<String> values) {
			addCriterion("card7_nm in", values, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmNotIn(List<String> values) {
			addCriterion("card7_nm not in", values, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmBetween(String value1, String value2) {
			addCriterion("card7_nm between", value1, value2, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCard7NmNotBetween(String value1, String value2) {
			addCriterion("card7_nm not between", value1, value2, "card7Nm");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("create_user like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("create_user not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIsNull() {
			addCriterion("create_pgid is null");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIsNotNull() {
			addCriterion("create_pgid is not null");
			return (Criteria) this;
		}

		public Criteria andCreatePgidEqualTo(String value) {
			addCriterion("create_pgid =", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotEqualTo(String value) {
			addCriterion("create_pgid <>", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidGreaterThan(String value) {
			addCriterion("create_pgid >", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidGreaterThanOrEqualTo(String value) {
			addCriterion("create_pgid >=", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLessThan(String value) {
			addCriterion("create_pgid <", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLessThanOrEqualTo(String value) {
			addCriterion("create_pgid <=", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLike(String value) {
			addCriterion("create_pgid like", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotLike(String value) {
			addCriterion("create_pgid not like", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIn(List<String> values) {
			addCriterion("create_pgid in", values, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotIn(List<String> values) {
			addCriterion("create_pgid not in", values, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidBetween(String value1, String value2) {
			addCriterion("create_pgid between", value1, value2, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotBetween(String value1, String value2) {
			addCriterion("create_pgid not between", value1, value2, "createPgid");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIsNull() {
			addCriterion("update_pgid is null");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIsNotNull() {
			addCriterion("update_pgid is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidEqualTo(String value) {
			addCriterion("update_pgid =", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotEqualTo(String value) {
			addCriterion("update_pgid <>", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidGreaterThan(String value) {
			addCriterion("update_pgid >", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidGreaterThanOrEqualTo(String value) {
			addCriterion("update_pgid >=", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLessThan(String value) {
			addCriterion("update_pgid <", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLessThanOrEqualTo(String value) {
			addCriterion("update_pgid <=", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLike(String value) {
			addCriterion("update_pgid like", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotLike(String value) {
			addCriterion("update_pgid not like", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIn(List<String> values) {
			addCriterion("update_pgid in", values, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotIn(List<String> values) {
			addCriterion("update_pgid not in", values, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidBetween(String value1, String value2) {
			addCriterion("update_pgid between", value1, value2, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotBetween(String value1, String value2) {
			addCriterion("update_pgid not between", value1, value2, "updatePgid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cards_retain
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 09 11:00:15 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}