package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class CardsRetain extends CardsRetainKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.empcard_owner
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String empcardOwner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card1_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card1Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card2_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card2Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card3_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card3Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card4_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card4Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card5_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card5Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card6_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card6Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.card7_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String card7Nm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.create_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.create_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.create_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String createPgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.update_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.update_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cards_retain.update_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	private String updatePgid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.empcard_owner
	 * @return  the value of cards_retain.empcard_owner
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getEmpcardOwner() {
		return empcardOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.empcard_owner
	 * @param empcardOwner  the value for cards_retain.empcard_owner
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setEmpcardOwner(String empcardOwner) {
		this.empcardOwner = empcardOwner == null ? null : empcardOwner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card1_nm
	 * @return  the value of cards_retain.card1_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard1Nm() {
		return card1Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card1_nm
	 * @param card1Nm  the value for cards_retain.card1_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard1Nm(String card1Nm) {
		this.card1Nm = card1Nm == null ? null : card1Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card2_nm
	 * @return  the value of cards_retain.card2_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard2Nm() {
		return card2Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card2_nm
	 * @param card2Nm  the value for cards_retain.card2_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard2Nm(String card2Nm) {
		this.card2Nm = card2Nm == null ? null : card2Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card3_nm
	 * @return  the value of cards_retain.card3_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard3Nm() {
		return card3Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card3_nm
	 * @param card3Nm  the value for cards_retain.card3_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard3Nm(String card3Nm) {
		this.card3Nm = card3Nm == null ? null : card3Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card4_nm
	 * @return  the value of cards_retain.card4_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard4Nm() {
		return card4Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card4_nm
	 * @param card4Nm  the value for cards_retain.card4_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard4Nm(String card4Nm) {
		this.card4Nm = card4Nm == null ? null : card4Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card5_nm
	 * @return  the value of cards_retain.card5_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard5Nm() {
		return card5Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card5_nm
	 * @param card5Nm  the value for cards_retain.card5_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard5Nm(String card5Nm) {
		this.card5Nm = card5Nm == null ? null : card5Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card6_nm
	 * @return  the value of cards_retain.card6_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard6Nm() {
		return card6Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card6_nm
	 * @param card6Nm  the value for cards_retain.card6_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard6Nm(String card6Nm) {
		this.card6Nm = card6Nm == null ? null : card6Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.card7_nm
	 * @return  the value of cards_retain.card7_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCard7Nm() {
		return card7Nm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.card7_nm
	 * @param card7Nm  the value for cards_retain.card7_nm
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCard7Nm(String card7Nm) {
		this.card7Nm = card7Nm == null ? null : card7Nm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.create_user
	 * @return  the value of cards_retain.create_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.create_user
	 * @param createUser  the value for cards_retain.create_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.create_date
	 * @return  the value of cards_retain.create_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.create_date
	 * @param createDate  the value for cards_retain.create_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.create_pgid
	 * @return  the value of cards_retain.create_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getCreatePgid() {
		return createPgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.create_pgid
	 * @param createPgid  the value for cards_retain.create_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setCreatePgid(String createPgid) {
		this.createPgid = createPgid == null ? null : createPgid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.update_user
	 * @return  the value of cards_retain.update_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.update_user
	 * @param updateUser  the value for cards_retain.update_user
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.update_date
	 * @return  the value of cards_retain.update_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.update_date
	 * @param updateDate  the value for cards_retain.update_date
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cards_retain.update_pgid
	 * @return  the value of cards_retain.update_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public String getUpdatePgid() {
		return updatePgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cards_retain.update_pgid
	 * @param updatePgid  the value for cards_retain.update_pgid
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	public void setUpdatePgid(String updatePgid) {
		this.updatePgid = updatePgid == null ? null : updatePgid.trim();
	}
}