package sp.co.soe.emp.domain.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Entity
@Table(name = "departments")
public class Departments {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.dept_code
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    @Id
    private String deptCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.dept_name
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private String deptName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.create_user
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private String createUser;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.create_date
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private Date createDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.create_pgid
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private String createPgid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.update_user
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private String updateUser;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.update_date
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private Date updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column departments.update_pgid
     *
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.dept_code
     *
     * @return the value of departments.dept_code
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.dept_code
     *
     * @param deptCode the value for departments.dept_code
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.dept_name
     *
     * @return the value of departments.dept_name
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.dept_name
     *
     * @param deptName the value for departments.dept_name
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.create_user
     *
     * @return the value of departments.create_user
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.create_user
     *
     * @param createUser the value for departments.create_user
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.create_date
     *
     * @return the value of departments.create_date
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.create_date
     *
     * @param createDate the value for departments.create_date
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.create_pgid
     *
     * @return the value of departments.create_pgid
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.create_pgid
     *
     * @param createPgid the value for departments.create_pgid
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.update_user
     *
     * @return the value of departments.update_user
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.update_user
     *
     * @param updateUser the value for departments.update_user
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.update_date
     *
     * @return the value of departments.update_date
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.update_date
     *
     * @param updateDate the value for departments.update_date
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column departments.update_pgid
     *
     * @return the value of departments.update_pgid
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column departments.update_pgid
     *
     * @param updatePgid the value for departments.update_pgid
     * @mbg.generated Sat Apr 04 17:59:08 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}