package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class EmployeesM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.employee_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.first_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.last_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.grade_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String gradeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.post_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.dept_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.sex
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.union_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String unionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.joining_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date joiningDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.retire_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date retireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.delete_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.mail_address
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.comm_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Boolean commCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.manage_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String manageFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String createPgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees_m.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.employee_id
     *
     * @return the value of employees_m.employee_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.employee_id
     *
     * @param employeeId the value for employees_m.employee_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.first_name
     *
     * @return the value of employees_m.first_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.first_name
     *
     * @param firstName the value for employees_m.first_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.last_name
     *
     * @return the value of employees_m.last_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.last_name
     *
     * @param lastName the value for employees_m.last_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.grade_code
     *
     * @return the value of employees_m.grade_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getGradeCode() {
        return gradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.grade_code
     *
     * @param gradeCode the value for employees_m.grade_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode == null ? null : gradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.post_code
     *
     * @return the value of employees_m.post_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.post_code
     *
     * @param postCode the value for employees_m.post_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.dept_code
     *
     * @return the value of employees_m.dept_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.dept_code
     *
     * @param deptCode the value for employees_m.dept_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.sex
     *
     * @return the value of employees_m.sex
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.sex
     *
     * @param sex the value for employees_m.sex
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.union_name
     *
     * @return the value of employees_m.union_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getUnionName() {
        return unionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.union_name
     *
     * @param unionName the value for employees_m.union_name
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUnionName(String unionName) {
        this.unionName = unionName == null ? null : unionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.joining_date
     *
     * @return the value of employees_m.joining_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getJoiningDate() {
        return joiningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.joining_date
     *
     * @param joiningDate the value for employees_m.joining_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.retire_date
     *
     * @return the value of employees_m.retire_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getRetireDate() {
        return retireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.retire_date
     *
     * @param retireDate the value for employees_m.retire_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setRetireDate(Date retireDate) {
        this.retireDate = retireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.delete_flg
     *
     * @return the value of employees_m.delete_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.delete_flg
     *
     * @param deleteFlg the value for employees_m.delete_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.mail_address
     *
     * @return the value of employees_m.mail_address
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.mail_address
     *
     * @param mailAddress the value for employees_m.mail_address
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.comm_code
     *
     * @return the value of employees_m.comm_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Boolean getCommCode() {
        return commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.comm_code
     *
     * @param commCode the value for employees_m.comm_code
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCommCode(Boolean commCode) {
        this.commCode = commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.manage_flg
     *
     * @return the value of employees_m.manage_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getManageFlg() {
        return manageFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.manage_flg
     *
     * @param manageFlg the value for employees_m.manage_flg
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setManageFlg(String manageFlg) {
        this.manageFlg = manageFlg == null ? null : manageFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.create_user
     *
     * @return the value of employees_m.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.create_user
     *
     * @param createUser the value for employees_m.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.create_date
     *
     * @return the value of employees_m.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.create_date
     *
     * @param createDate the value for employees_m.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.create_pgid
     *
     * @return the value of employees_m.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.create_pgid
     *
     * @param createPgid the value for employees_m.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.update_user
     *
     * @return the value of employees_m.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.update_user
     *
     * @param updateUser the value for employees_m.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.update_date
     *
     * @return the value of employees_m.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.update_date
     *
     * @param updateDate the value for employees_m.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees_m.update_pgid
     *
     * @return the value of employees_m.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees_m.update_pgid
     *
     * @param updatePgid the value for employees_m.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}