package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class JobPosts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.post_code
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.post_name
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.create_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.create_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.create_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String createPgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.update_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.update_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job_posts.update_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	private String updatePgid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.post_code
	 * @return  the value of job_posts.post_code
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.post_code
	 * @param postCode  the value for job_posts.post_code
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode == null ? null : postCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.post_name
	 * @return  the value of job_posts.post_name
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.post_name
	 * @param postName  the value for job_posts.post_name
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setPostName(String postName) {
		this.postName = postName == null ? null : postName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.create_user
	 * @return  the value of job_posts.create_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.create_user
	 * @param createUser  the value for job_posts.create_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.create_date
	 * @return  the value of job_posts.create_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.create_date
	 * @param createDate  the value for job_posts.create_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.create_pgid
	 * @return  the value of job_posts.create_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getCreatePgid() {
		return createPgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.create_pgid
	 * @param createPgid  the value for job_posts.create_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setCreatePgid(String createPgid) {
		this.createPgid = createPgid == null ? null : createPgid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.update_user
	 * @return  the value of job_posts.update_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.update_user
	 * @param updateUser  the value for job_posts.update_user
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.update_date
	 * @return  the value of job_posts.update_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.update_date
	 * @param updateDate  the value for job_posts.update_date
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job_posts.update_pgid
	 * @return  the value of job_posts.update_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public String getUpdatePgid() {
		return updatePgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job_posts.update_pgid
	 * @param updatePgid  the value for job_posts.update_pgid
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	public void setUpdatePgid(String updatePgid) {
		this.updatePgid = updatePgid == null ? null : updatePgid.trim();
	}
}