package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class Menus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menu_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createPgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menu_id
     *
     * @return the value of menus.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menu_id
     *
     * @param menuId the value for menus.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menu_name
     *
     * @return the value of menus.menu_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menu_name
     *
     * @param menuName the value for menus.menu_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.description
     *
     * @return the value of menus.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.description
     *
     * @param description the value for menus.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.create_user
     *
     * @return the value of menus.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.create_user
     *
     * @param createUser the value for menus.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.create_date
     *
     * @return the value of menus.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.create_date
     *
     * @param createDate the value for menus.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.create_pgid
     *
     * @return the value of menus.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.create_pgid
     *
     * @param createPgid the value for menus.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.update_user
     *
     * @return the value of menus.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.update_user
     *
     * @param updateUser the value for menus.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.update_date
     *
     * @return the value of menus.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.update_date
     *
     * @param updateDate the value for menus.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.update_pgid
     *
     * @return the value of menus.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.update_pgid
     *
     * @param updatePgid the value for menus.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}