package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createPgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_id
     *
     * @return the value of roles.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_id
     *
     * @param roleId the value for roles.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_name
     *
     * @return the value of roles.role_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_name
     *
     * @param roleName the value for roles.role_name
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.description
     *
     * @return the value of roles.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.description
     *
     * @param description the value for roles.description
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.create_user
     *
     * @return the value of roles.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.create_user
     *
     * @param createUser the value for roles.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.create_date
     *
     * @return the value of roles.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.create_date
     *
     * @param createDate the value for roles.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.create_pgid
     *
     * @return the value of roles.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.create_pgid
     *
     * @param createPgid the value for roles.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.update_user
     *
     * @return the value of roles.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.update_user
     *
     * @param updateUser the value for roles.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.update_date
     *
     * @return the value of roles.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.update_date
     *
     * @param updateDate the value for roles.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.update_pgid
     *
     * @return the value of roles.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.update_pgid
     *
     * @param updatePgid the value for roles.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}