package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class RoleMenuPermissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.role_menu_permission_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Integer roleMenuPermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String createPgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.role_menu_permission_id
     *
     * @return the value of role_menu_permissions.role_menu_permission_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Integer getRoleMenuPermissionId() {
        return roleMenuPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.role_menu_permission_id
     *
     * @param roleMenuPermissionId the value for role_menu_permissions.role_menu_permission_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setRoleMenuPermissionId(Integer roleMenuPermissionId) {
        this.roleMenuPermissionId = roleMenuPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.menu_id
     *
     * @return the value of role_menu_permissions.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.menu_id
     *
     * @param menuId the value for role_menu_permissions.menu_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.role_id
     *
     * @return the value of role_menu_permissions.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.role_id
     *
     * @param roleId the value for role_menu_permissions.role_id
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.create_user
     *
     * @return the value of role_menu_permissions.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.create_user
     *
     * @param createUser the value for role_menu_permissions.create_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.create_date
     *
     * @return the value of role_menu_permissions.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.create_date
     *
     * @param createDate the value for role_menu_permissions.create_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.create_pgid
     *
     * @return the value of role_menu_permissions.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.create_pgid
     *
     * @param createPgid the value for role_menu_permissions.create_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.update_user
     *
     * @return the value of role_menu_permissions.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.update_user
     *
     * @param updateUser the value for role_menu_permissions.update_user
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.update_date
     *
     * @return the value of role_menu_permissions.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.update_date
     *
     * @param updateDate the value for role_menu_permissions.update_date
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.update_pgid
     *
     * @return the value of role_menu_permissions.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.update_pgid
     *
     * @param updatePgid the value for role_menu_permissions.update_pgid
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}