package sp.co.soe.emp.domain.entity;

import java.util.Date;

public class SystemParams {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_nm1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramNm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_nm2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramNm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_nm3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramNm3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_nm4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramNm4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_cd1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramCd1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_cd2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramCd2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_cd3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramCd3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_cd4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String paramCd4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_date1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date paramDate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_date2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date paramDate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_date3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date paramDate3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.param_date4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date paramDate4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String createPgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_params.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    private String updatePgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_id
     *
     * @return the value of system_params.param_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_id
     *
     * @param paramId the value for system_params.param_id
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamId(String paramId) {
        this.paramId = paramId == null ? null : paramId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_nm1
     *
     * @return the value of system_params.param_nm1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamNm1() {
        return paramNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_nm1
     *
     * @param paramNm1 the value for system_params.param_nm1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamNm1(String paramNm1) {
        this.paramNm1 = paramNm1 == null ? null : paramNm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_nm2
     *
     * @return the value of system_params.param_nm2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamNm2() {
        return paramNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_nm2
     *
     * @param paramNm2 the value for system_params.param_nm2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamNm2(String paramNm2) {
        this.paramNm2 = paramNm2 == null ? null : paramNm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_nm3
     *
     * @return the value of system_params.param_nm3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamNm3() {
        return paramNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_nm3
     *
     * @param paramNm3 the value for system_params.param_nm3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamNm3(String paramNm3) {
        this.paramNm3 = paramNm3 == null ? null : paramNm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_nm4
     *
     * @return the value of system_params.param_nm4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamNm4() {
        return paramNm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_nm4
     *
     * @param paramNm4 the value for system_params.param_nm4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamNm4(String paramNm4) {
        this.paramNm4 = paramNm4 == null ? null : paramNm4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_cd1
     *
     * @return the value of system_params.param_cd1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamCd1() {
        return paramCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_cd1
     *
     * @param paramCd1 the value for system_params.param_cd1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamCd1(String paramCd1) {
        this.paramCd1 = paramCd1 == null ? null : paramCd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_cd2
     *
     * @return the value of system_params.param_cd2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamCd2() {
        return paramCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_cd2
     *
     * @param paramCd2 the value for system_params.param_cd2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamCd2(String paramCd2) {
        this.paramCd2 = paramCd2 == null ? null : paramCd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_cd3
     *
     * @return the value of system_params.param_cd3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamCd3() {
        return paramCd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_cd3
     *
     * @param paramCd3 the value for system_params.param_cd3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamCd3(String paramCd3) {
        this.paramCd3 = paramCd3 == null ? null : paramCd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_cd4
     *
     * @return the value of system_params.param_cd4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getParamCd4() {
        return paramCd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_cd4
     *
     * @param paramCd4 the value for system_params.param_cd4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamCd4(String paramCd4) {
        this.paramCd4 = paramCd4 == null ? null : paramCd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_date1
     *
     * @return the value of system_params.param_date1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getParamDate1() {
        return paramDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_date1
     *
     * @param paramDate1 the value for system_params.param_date1
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamDate1(Date paramDate1) {
        this.paramDate1 = paramDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_date2
     *
     * @return the value of system_params.param_date2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getParamDate2() {
        return paramDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_date2
     *
     * @param paramDate2 the value for system_params.param_date2
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamDate2(Date paramDate2) {
        this.paramDate2 = paramDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_date3
     *
     * @return the value of system_params.param_date3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getParamDate3() {
        return paramDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_date3
     *
     * @param paramDate3 the value for system_params.param_date3
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamDate3(Date paramDate3) {
        this.paramDate3 = paramDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.param_date4
     *
     * @return the value of system_params.param_date4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getParamDate4() {
        return paramDate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.param_date4
     *
     * @param paramDate4 the value for system_params.param_date4
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setParamDate4(Date paramDate4) {
        this.paramDate4 = paramDate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.create_user
     *
     * @return the value of system_params.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.create_user
     *
     * @param createUser the value for system_params.create_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.create_date
     *
     * @return the value of system_params.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.create_date
     *
     * @param createDate the value for system_params.create_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.create_pgid
     *
     * @return the value of system_params.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getCreatePgid() {
        return createPgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.create_pgid
     *
     * @param createPgid the value for system_params.create_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setCreatePgid(String createPgid) {
        this.createPgid = createPgid == null ? null : createPgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.update_user
     *
     * @return the value of system_params.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.update_user
     *
     * @param updateUser the value for system_params.update_user
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.update_date
     *
     * @return the value of system_params.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.update_date
     *
     * @param updateDate the value for system_params.update_date
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_params.update_pgid
     *
     * @return the value of system_params.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getUpdatePgid() {
        return updatePgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_params.update_pgid
     *
     * @param updatePgid the value for system_params.update_pgid
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setUpdatePgid(String updatePgid) {
        this.updatePgid = updatePgid == null ? null : updatePgid.trim();
    }
}