package sp.co.soe.emp.domain.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component
public class SystemParamsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public SystemParamsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andParamIdIsNull() {
            addCriterion("param_id is null");
            return (Criteria) this;
        }

        public Criteria andParamIdIsNotNull() {
            addCriterion("param_id is not null");
            return (Criteria) this;
        }

        public Criteria andParamIdEqualTo(String value) {
            addCriterion("param_id =", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdNotEqualTo(String value) {
            addCriterion("param_id <>", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdGreaterThan(String value) {
            addCriterion("param_id >", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdGreaterThanOrEqualTo(String value) {
            addCriterion("param_id >=", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdLessThan(String value) {
            addCriterion("param_id <", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdLessThanOrEqualTo(String value) {
            addCriterion("param_id <=", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdLike(String value) {
            addCriterion("param_id like", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdNotLike(String value) {
            addCriterion("param_id not like", value, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdIn(List<String> values) {
            addCriterion("param_id in", values, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdNotIn(List<String> values) {
            addCriterion("param_id not in", values, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdBetween(String value1, String value2) {
            addCriterion("param_id between", value1, value2, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamIdNotBetween(String value1, String value2) {
            addCriterion("param_id not between", value1, value2, "paramId");
            return (Criteria) this;
        }

        public Criteria andParamNm1IsNull() {
            addCriterion("param_nm1 is null");
            return (Criteria) this;
        }

        public Criteria andParamNm1IsNotNull() {
            addCriterion("param_nm1 is not null");
            return (Criteria) this;
        }

        public Criteria andParamNm1EqualTo(String value) {
            addCriterion("param_nm1 =", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1NotEqualTo(String value) {
            addCriterion("param_nm1 <>", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1GreaterThan(String value) {
            addCriterion("param_nm1 >", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1GreaterThanOrEqualTo(String value) {
            addCriterion("param_nm1 >=", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1LessThan(String value) {
            addCriterion("param_nm1 <", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1LessThanOrEqualTo(String value) {
            addCriterion("param_nm1 <=", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1Like(String value) {
            addCriterion("param_nm1 like", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1NotLike(String value) {
            addCriterion("param_nm1 not like", value, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1In(List<String> values) {
            addCriterion("param_nm1 in", values, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1NotIn(List<String> values) {
            addCriterion("param_nm1 not in", values, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1Between(String value1, String value2) {
            addCriterion("param_nm1 between", value1, value2, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm1NotBetween(String value1, String value2) {
            addCriterion("param_nm1 not between", value1, value2, "paramNm1");
            return (Criteria) this;
        }

        public Criteria andParamNm2IsNull() {
            addCriterion("param_nm2 is null");
            return (Criteria) this;
        }

        public Criteria andParamNm2IsNotNull() {
            addCriterion("param_nm2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamNm2EqualTo(String value) {
            addCriterion("param_nm2 =", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2NotEqualTo(String value) {
            addCriterion("param_nm2 <>", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2GreaterThan(String value) {
            addCriterion("param_nm2 >", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2GreaterThanOrEqualTo(String value) {
            addCriterion("param_nm2 >=", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2LessThan(String value) {
            addCriterion("param_nm2 <", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2LessThanOrEqualTo(String value) {
            addCriterion("param_nm2 <=", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2Like(String value) {
            addCriterion("param_nm2 like", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2NotLike(String value) {
            addCriterion("param_nm2 not like", value, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2In(List<String> values) {
            addCriterion("param_nm2 in", values, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2NotIn(List<String> values) {
            addCriterion("param_nm2 not in", values, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2Between(String value1, String value2) {
            addCriterion("param_nm2 between", value1, value2, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm2NotBetween(String value1, String value2) {
            addCriterion("param_nm2 not between", value1, value2, "paramNm2");
            return (Criteria) this;
        }

        public Criteria andParamNm3IsNull() {
            addCriterion("param_nm3 is null");
            return (Criteria) this;
        }

        public Criteria andParamNm3IsNotNull() {
            addCriterion("param_nm3 is not null");
            return (Criteria) this;
        }

        public Criteria andParamNm3EqualTo(String value) {
            addCriterion("param_nm3 =", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3NotEqualTo(String value) {
            addCriterion("param_nm3 <>", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3GreaterThan(String value) {
            addCriterion("param_nm3 >", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3GreaterThanOrEqualTo(String value) {
            addCriterion("param_nm3 >=", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3LessThan(String value) {
            addCriterion("param_nm3 <", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3LessThanOrEqualTo(String value) {
            addCriterion("param_nm3 <=", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3Like(String value) {
            addCriterion("param_nm3 like", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3NotLike(String value) {
            addCriterion("param_nm3 not like", value, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3In(List<String> values) {
            addCriterion("param_nm3 in", values, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3NotIn(List<String> values) {
            addCriterion("param_nm3 not in", values, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3Between(String value1, String value2) {
            addCriterion("param_nm3 between", value1, value2, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm3NotBetween(String value1, String value2) {
            addCriterion("param_nm3 not between", value1, value2, "paramNm3");
            return (Criteria) this;
        }

        public Criteria andParamNm4IsNull() {
            addCriterion("param_nm4 is null");
            return (Criteria) this;
        }

        public Criteria andParamNm4IsNotNull() {
            addCriterion("param_nm4 is not null");
            return (Criteria) this;
        }

        public Criteria andParamNm4EqualTo(String value) {
            addCriterion("param_nm4 =", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4NotEqualTo(String value) {
            addCriterion("param_nm4 <>", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4GreaterThan(String value) {
            addCriterion("param_nm4 >", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4GreaterThanOrEqualTo(String value) {
            addCriterion("param_nm4 >=", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4LessThan(String value) {
            addCriterion("param_nm4 <", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4LessThanOrEqualTo(String value) {
            addCriterion("param_nm4 <=", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4Like(String value) {
            addCriterion("param_nm4 like", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4NotLike(String value) {
            addCriterion("param_nm4 not like", value, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4In(List<String> values) {
            addCriterion("param_nm4 in", values, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4NotIn(List<String> values) {
            addCriterion("param_nm4 not in", values, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4Between(String value1, String value2) {
            addCriterion("param_nm4 between", value1, value2, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamNm4NotBetween(String value1, String value2) {
            addCriterion("param_nm4 not between", value1, value2, "paramNm4");
            return (Criteria) this;
        }

        public Criteria andParamCd1IsNull() {
            addCriterion("param_cd1 is null");
            return (Criteria) this;
        }

        public Criteria andParamCd1IsNotNull() {
            addCriterion("param_cd1 is not null");
            return (Criteria) this;
        }

        public Criteria andParamCd1EqualTo(String value) {
            addCriterion("param_cd1 =", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1NotEqualTo(String value) {
            addCriterion("param_cd1 <>", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1GreaterThan(String value) {
            addCriterion("param_cd1 >", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1GreaterThanOrEqualTo(String value) {
            addCriterion("param_cd1 >=", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1LessThan(String value) {
            addCriterion("param_cd1 <", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1LessThanOrEqualTo(String value) {
            addCriterion("param_cd1 <=", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1Like(String value) {
            addCriterion("param_cd1 like", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1NotLike(String value) {
            addCriterion("param_cd1 not like", value, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1In(List<String> values) {
            addCriterion("param_cd1 in", values, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1NotIn(List<String> values) {
            addCriterion("param_cd1 not in", values, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1Between(String value1, String value2) {
            addCriterion("param_cd1 between", value1, value2, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd1NotBetween(String value1, String value2) {
            addCriterion("param_cd1 not between", value1, value2, "paramCd1");
            return (Criteria) this;
        }

        public Criteria andParamCd2IsNull() {
            addCriterion("param_cd2 is null");
            return (Criteria) this;
        }

        public Criteria andParamCd2IsNotNull() {
            addCriterion("param_cd2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamCd2EqualTo(String value) {
            addCriterion("param_cd2 =", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2NotEqualTo(String value) {
            addCriterion("param_cd2 <>", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2GreaterThan(String value) {
            addCriterion("param_cd2 >", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2GreaterThanOrEqualTo(String value) {
            addCriterion("param_cd2 >=", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2LessThan(String value) {
            addCriterion("param_cd2 <", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2LessThanOrEqualTo(String value) {
            addCriterion("param_cd2 <=", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2Like(String value) {
            addCriterion("param_cd2 like", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2NotLike(String value) {
            addCriterion("param_cd2 not like", value, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2In(List<String> values) {
            addCriterion("param_cd2 in", values, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2NotIn(List<String> values) {
            addCriterion("param_cd2 not in", values, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2Between(String value1, String value2) {
            addCriterion("param_cd2 between", value1, value2, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd2NotBetween(String value1, String value2) {
            addCriterion("param_cd2 not between", value1, value2, "paramCd2");
            return (Criteria) this;
        }

        public Criteria andParamCd3IsNull() {
            addCriterion("param_cd3 is null");
            return (Criteria) this;
        }

        public Criteria andParamCd3IsNotNull() {
            addCriterion("param_cd3 is not null");
            return (Criteria) this;
        }

        public Criteria andParamCd3EqualTo(String value) {
            addCriterion("param_cd3 =", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3NotEqualTo(String value) {
            addCriterion("param_cd3 <>", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3GreaterThan(String value) {
            addCriterion("param_cd3 >", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3GreaterThanOrEqualTo(String value) {
            addCriterion("param_cd3 >=", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3LessThan(String value) {
            addCriterion("param_cd3 <", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3LessThanOrEqualTo(String value) {
            addCriterion("param_cd3 <=", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3Like(String value) {
            addCriterion("param_cd3 like", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3NotLike(String value) {
            addCriterion("param_cd3 not like", value, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3In(List<String> values) {
            addCriterion("param_cd3 in", values, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3NotIn(List<String> values) {
            addCriterion("param_cd3 not in", values, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3Between(String value1, String value2) {
            addCriterion("param_cd3 between", value1, value2, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd3NotBetween(String value1, String value2) {
            addCriterion("param_cd3 not between", value1, value2, "paramCd3");
            return (Criteria) this;
        }

        public Criteria andParamCd4IsNull() {
            addCriterion("param_cd4 is null");
            return (Criteria) this;
        }

        public Criteria andParamCd4IsNotNull() {
            addCriterion("param_cd4 is not null");
            return (Criteria) this;
        }

        public Criteria andParamCd4EqualTo(String value) {
            addCriterion("param_cd4 =", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4NotEqualTo(String value) {
            addCriterion("param_cd4 <>", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4GreaterThan(String value) {
            addCriterion("param_cd4 >", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4GreaterThanOrEqualTo(String value) {
            addCriterion("param_cd4 >=", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4LessThan(String value) {
            addCriterion("param_cd4 <", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4LessThanOrEqualTo(String value) {
            addCriterion("param_cd4 <=", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4Like(String value) {
            addCriterion("param_cd4 like", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4NotLike(String value) {
            addCriterion("param_cd4 not like", value, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4In(List<String> values) {
            addCriterion("param_cd4 in", values, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4NotIn(List<String> values) {
            addCriterion("param_cd4 not in", values, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4Between(String value1, String value2) {
            addCriterion("param_cd4 between", value1, value2, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamCd4NotBetween(String value1, String value2) {
            addCriterion("param_cd4 not between", value1, value2, "paramCd4");
            return (Criteria) this;
        }

        public Criteria andParamDate1IsNull() {
            addCriterion("param_date1 is null");
            return (Criteria) this;
        }

        public Criteria andParamDate1IsNotNull() {
            addCriterion("param_date1 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDate1EqualTo(Date value) {
            addCriterion("param_date1 =", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1NotEqualTo(Date value) {
            addCriterion("param_date1 <>", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1GreaterThan(Date value) {
            addCriterion("param_date1 >", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1GreaterThanOrEqualTo(Date value) {
            addCriterion("param_date1 >=", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1LessThan(Date value) {
            addCriterion("param_date1 <", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1LessThanOrEqualTo(Date value) {
            addCriterion("param_date1 <=", value, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1In(List<Date> values) {
            addCriterion("param_date1 in", values, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1NotIn(List<Date> values) {
            addCriterion("param_date1 not in", values, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1Between(Date value1, Date value2) {
            addCriterion("param_date1 between", value1, value2, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate1NotBetween(Date value1, Date value2) {
            addCriterion("param_date1 not between", value1, value2, "paramDate1");
            return (Criteria) this;
        }

        public Criteria andParamDate2IsNull() {
            addCriterion("param_date2 is null");
            return (Criteria) this;
        }

        public Criteria andParamDate2IsNotNull() {
            addCriterion("param_date2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDate2EqualTo(Date value) {
            addCriterion("param_date2 =", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2NotEqualTo(Date value) {
            addCriterion("param_date2 <>", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2GreaterThan(Date value) {
            addCriterion("param_date2 >", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2GreaterThanOrEqualTo(Date value) {
            addCriterion("param_date2 >=", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2LessThan(Date value) {
            addCriterion("param_date2 <", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2LessThanOrEqualTo(Date value) {
            addCriterion("param_date2 <=", value, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2In(List<Date> values) {
            addCriterion("param_date2 in", values, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2NotIn(List<Date> values) {
            addCriterion("param_date2 not in", values, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2Between(Date value1, Date value2) {
            addCriterion("param_date2 between", value1, value2, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate2NotBetween(Date value1, Date value2) {
            addCriterion("param_date2 not between", value1, value2, "paramDate2");
            return (Criteria) this;
        }

        public Criteria andParamDate3IsNull() {
            addCriterion("param_date3 is null");
            return (Criteria) this;
        }

        public Criteria andParamDate3IsNotNull() {
            addCriterion("param_date3 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDate3EqualTo(Date value) {
            addCriterion("param_date3 =", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3NotEqualTo(Date value) {
            addCriterion("param_date3 <>", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3GreaterThan(Date value) {
            addCriterion("param_date3 >", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3GreaterThanOrEqualTo(Date value) {
            addCriterion("param_date3 >=", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3LessThan(Date value) {
            addCriterion("param_date3 <", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3LessThanOrEqualTo(Date value) {
            addCriterion("param_date3 <=", value, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3In(List<Date> values) {
            addCriterion("param_date3 in", values, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3NotIn(List<Date> values) {
            addCriterion("param_date3 not in", values, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3Between(Date value1, Date value2) {
            addCriterion("param_date3 between", value1, value2, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate3NotBetween(Date value1, Date value2) {
            addCriterion("param_date3 not between", value1, value2, "paramDate3");
            return (Criteria) this;
        }

        public Criteria andParamDate4IsNull() {
            addCriterion("param_date4 is null");
            return (Criteria) this;
        }

        public Criteria andParamDate4IsNotNull() {
            addCriterion("param_date4 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDate4EqualTo(Date value) {
            addCriterion("param_date4 =", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4NotEqualTo(Date value) {
            addCriterion("param_date4 <>", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4GreaterThan(Date value) {
            addCriterion("param_date4 >", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4GreaterThanOrEqualTo(Date value) {
            addCriterion("param_date4 >=", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4LessThan(Date value) {
            addCriterion("param_date4 <", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4LessThanOrEqualTo(Date value) {
            addCriterion("param_date4 <=", value, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4In(List<Date> values) {
            addCriterion("param_date4 in", values, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4NotIn(List<Date> values) {
            addCriterion("param_date4 not in", values, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4Between(Date value1, Date value2) {
            addCriterion("param_date4 between", value1, value2, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andParamDate4NotBetween(Date value1, Date value2) {
            addCriterion("param_date4 not between", value1, value2, "paramDate4");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreatePgidIsNull() {
            addCriterion("create_pgid is null");
            return (Criteria) this;
        }

        public Criteria andCreatePgidIsNotNull() {
            addCriterion("create_pgid is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePgidEqualTo(String value) {
            addCriterion("create_pgid =", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidNotEqualTo(String value) {
            addCriterion("create_pgid <>", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidGreaterThan(String value) {
            addCriterion("create_pgid >", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidGreaterThanOrEqualTo(String value) {
            addCriterion("create_pgid >=", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidLessThan(String value) {
            addCriterion("create_pgid <", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidLessThanOrEqualTo(String value) {
            addCriterion("create_pgid <=", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidLike(String value) {
            addCriterion("create_pgid like", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidNotLike(String value) {
            addCriterion("create_pgid not like", value, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidIn(List<String> values) {
            addCriterion("create_pgid in", values, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidNotIn(List<String> values) {
            addCriterion("create_pgid not in", values, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidBetween(String value1, String value2) {
            addCriterion("create_pgid between", value1, value2, "createPgid");
            return (Criteria) this;
        }

        public Criteria andCreatePgidNotBetween(String value1, String value2) {
            addCriterion("create_pgid not between", value1, value2, "createPgid");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidIsNull() {
            addCriterion("update_pgid is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidIsNotNull() {
            addCriterion("update_pgid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidEqualTo(String value) {
            addCriterion("update_pgid =", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidNotEqualTo(String value) {
            addCriterion("update_pgid <>", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidGreaterThan(String value) {
            addCriterion("update_pgid >", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidGreaterThanOrEqualTo(String value) {
            addCriterion("update_pgid >=", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidLessThan(String value) {
            addCriterion("update_pgid <", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidLessThanOrEqualTo(String value) {
            addCriterion("update_pgid <=", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidLike(String value) {
            addCriterion("update_pgid like", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidNotLike(String value) {
            addCriterion("update_pgid not like", value, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidIn(List<String> values) {
            addCriterion("update_pgid in", values, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidNotIn(List<String> values) {
            addCriterion("update_pgid not in", values, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidBetween(String value1, String value2) {
            addCriterion("update_pgid between", value1, value2, "updatePgid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgidNotBetween(String value1, String value2) {
            addCriterion("update_pgid not between", value1, value2, "updatePgid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_params
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 30 00:37:11 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_params
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}