package sp.co.soe.emp.domain.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

@Component
public class UsersAccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public UsersAccountExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateIsNull() {
			addCriterion("pwd_change_date is null");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateIsNotNull() {
			addCriterion("pwd_change_date is not null");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateEqualTo(Date value) {
			addCriterionForJDBCDate("pwd_change_date =", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("pwd_change_date <>", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateGreaterThan(Date value) {
			addCriterionForJDBCDate("pwd_change_date >", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pwd_change_date >=", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateLessThan(Date value) {
			addCriterionForJDBCDate("pwd_change_date <", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pwd_change_date <=", value, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateIn(List<Date> values) {
			addCriterionForJDBCDate("pwd_change_date in", values, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("pwd_change_date not in", values, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pwd_change_date between", value1, value2, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andPwdChangeDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pwd_change_date not between", value1, value2, "pwdChangeDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateIsNull() {
			addCriterion("validate_start_date is null");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateIsNotNull() {
			addCriterion("validate_start_date is not null");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateEqualTo(Date value) {
			addCriterionForJDBCDate("validate_start_date =", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("validate_start_date <>", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateGreaterThan(Date value) {
			addCriterionForJDBCDate("validate_start_date >", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("validate_start_date >=", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateLessThan(Date value) {
			addCriterionForJDBCDate("validate_start_date <", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("validate_start_date <=", value, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateIn(List<Date> values) {
			addCriterionForJDBCDate("validate_start_date in", values, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("validate_start_date not in", values, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("validate_start_date between", value1, value2, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateStartDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("validate_start_date not between", value1, value2, "validateStartDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateIsNull() {
			addCriterion("validate_end_date is null");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateIsNotNull() {
			addCriterion("validate_end_date is not null");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateEqualTo(Date value) {
			addCriterionForJDBCDate("validate_end_date =", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("validate_end_date <>", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateGreaterThan(Date value) {
			addCriterionForJDBCDate("validate_end_date >", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("validate_end_date >=", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateLessThan(Date value) {
			addCriterionForJDBCDate("validate_end_date <", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("validate_end_date <=", value, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateIn(List<Date> values) {
			addCriterionForJDBCDate("validate_end_date in", values, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("validate_end_date not in", values, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("validate_end_date between", value1, value2, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andValidateEndDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("validate_end_date not between", value1, value2, "validateEndDate");
			return (Criteria) this;
		}

		public Criteria andActiveIsNull() {
			addCriterion("active is null");
			return (Criteria) this;
		}

		public Criteria andActiveIsNotNull() {
			addCriterion("active is not null");
			return (Criteria) this;
		}

		public Criteria andActiveEqualTo(Boolean value) {
			addCriterion("active =", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotEqualTo(Boolean value) {
			addCriterion("active <>", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThan(Boolean value) {
			addCriterion("active >", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("active >=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThan(Boolean value) {
			addCriterion("active <", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("active <=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveIn(List<Boolean> values) {
			addCriterion("active in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotIn(List<Boolean> values) {
			addCriterion("active not in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("active between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("active not between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andDeleteIsNull() {
			addCriterion("delete is null");
			return (Criteria) this;
		}

		public Criteria andDeleteIsNotNull() {
			addCriterion("delete is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteEqualTo(Boolean value) {
			addCriterion("delete =", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteNotEqualTo(Boolean value) {
			addCriterion("delete <>", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteGreaterThan(Boolean value) {
			addCriterion("delete >", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteGreaterThanOrEqualTo(Boolean value) {
			addCriterion("delete >=", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteLessThan(Boolean value) {
			addCriterion("delete <", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteLessThanOrEqualTo(Boolean value) {
			addCriterion("delete <=", value, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteIn(List<Boolean> values) {
			addCriterion("delete in", values, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteNotIn(List<Boolean> values) {
			addCriterion("delete not in", values, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteBetween(Boolean value1, Boolean value2) {
			addCriterion("delete between", value1, value2, "delete");
			return (Criteria) this;
		}

		public Criteria andDeleteNotBetween(Boolean value1, Boolean value2) {
			addCriterion("delete not between", value1, value2, "delete");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("create_user like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("create_user not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIsNull() {
			addCriterion("create_pgid is null");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIsNotNull() {
			addCriterion("create_pgid is not null");
			return (Criteria) this;
		}

		public Criteria andCreatePgidEqualTo(String value) {
			addCriterion("create_pgid =", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotEqualTo(String value) {
			addCriterion("create_pgid <>", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidGreaterThan(String value) {
			addCriterion("create_pgid >", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidGreaterThanOrEqualTo(String value) {
			addCriterion("create_pgid >=", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLessThan(String value) {
			addCriterion("create_pgid <", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLessThanOrEqualTo(String value) {
			addCriterion("create_pgid <=", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidLike(String value) {
			addCriterion("create_pgid like", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotLike(String value) {
			addCriterion("create_pgid not like", value, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidIn(List<String> values) {
			addCriterion("create_pgid in", values, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotIn(List<String> values) {
			addCriterion("create_pgid not in", values, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidBetween(String value1, String value2) {
			addCriterion("create_pgid between", value1, value2, "createPgid");
			return (Criteria) this;
		}

		public Criteria andCreatePgidNotBetween(String value1, String value2) {
			addCriterion("create_pgid not between", value1, value2, "createPgid");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIsNull() {
			addCriterion("update_pgid is null");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIsNotNull() {
			addCriterion("update_pgid is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidEqualTo(String value) {
			addCriterion("update_pgid =", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotEqualTo(String value) {
			addCriterion("update_pgid <>", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidGreaterThan(String value) {
			addCriterion("update_pgid >", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidGreaterThanOrEqualTo(String value) {
			addCriterion("update_pgid >=", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLessThan(String value) {
			addCriterion("update_pgid <", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLessThanOrEqualTo(String value) {
			addCriterion("update_pgid <=", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidLike(String value) {
			addCriterion("update_pgid like", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotLike(String value) {
			addCriterion("update_pgid not like", value, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidIn(List<String> values) {
			addCriterion("update_pgid in", values, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotIn(List<String> values) {
			addCriterion("update_pgid not in", values, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidBetween(String value1, String value2) {
			addCriterion("update_pgid between", value1, value2, "updatePgid");
			return (Criteria) this;
		}

		public Criteria andUpdatePgidNotBetween(String value1, String value2) {
			addCriterion("update_pgid not between", value1, value2, "updatePgid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_account
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 24 22:44:10 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}