package sp.co.soe.emp.domain.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

public class UsersAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.user_name
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.password
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.pwd_change_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Date pwdChangeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.validate_start_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Date validateStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.validate_end_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Date validateEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.active
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Boolean active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.delete
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Boolean delete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.create_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.create_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.create_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String createPgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.update_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.update_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_account.update_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	private String updatePgid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.user_name
	 * @return  the value of users_account.user_name
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.user_name
	 * @param userName  the value for users_account.user_name
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.password
	 * @return  the value of users_account.password
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.password
	 * @param password  the value for users_account.password
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.pwd_change_date
	 * @return  the value of users_account.pwd_change_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Date getPwdChangeDate() {
		return pwdChangeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.pwd_change_date
	 * @param pwdChangeDate  the value for users_account.pwd_change_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setPwdChangeDate(Date pwdChangeDate) {
		this.pwdChangeDate = pwdChangeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.validate_start_date
	 * @return  the value of users_account.validate_start_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Date getValidateStartDate() {
		return validateStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.validate_start_date
	 * @param validateStartDate  the value for users_account.validate_start_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setValidateStartDate(Date validateStartDate) {
		this.validateStartDate = validateStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.validate_end_date
	 * @return  the value of users_account.validate_end_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Date getValidateEndDate() {
		return validateEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.validate_end_date
	 * @param validateEndDate  the value for users_account.validate_end_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setValidateEndDate(Date validateEndDate) {
		this.validateEndDate = validateEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.active
	 * @return  the value of users_account.active
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.active
	 * @param active  the value for users_account.active
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.delete
	 * @return  the value of users_account.delete
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Boolean getDelete() {
		return delete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.delete
	 * @param delete  the value for users_account.delete
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setDelete(Boolean delete) {
		this.delete = delete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.create_user
	 * @return  the value of users_account.create_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.create_user
	 * @param createUser  the value for users_account.create_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.create_date
	 * @return  the value of users_account.create_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.create_date
	 * @param createDate  the value for users_account.create_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.create_pgid
	 * @return  the value of users_account.create_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getCreatePgid() {
		return createPgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.create_pgid
	 * @param createPgid  the value for users_account.create_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setCreatePgid(String createPgid) {
		this.createPgid = createPgid == null ? null : createPgid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.update_user
	 * @return  the value of users_account.update_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.update_user
	 * @param updateUser  the value for users_account.update_user
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.update_date
	 * @return  the value of users_account.update_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.update_date
	 * @param updateDate  the value for users_account.update_date
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_account.update_pgid
	 * @return  the value of users_account.update_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public String getUpdatePgid() {
		return updatePgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_account.update_pgid
	 * @param updatePgid  the value for users_account.update_pgid
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	public void setUpdatePgid(String updatePgid) {
		this.updatePgid = updatePgid == null ? null : updatePgid.trim();
	}
}