package sp.co.soe.emp.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import sp.co.soe.emp.domain.entity.CardsRetain;
import sp.co.soe.emp.domain.entity.CardsRetainExample;
import sp.co.soe.emp.domain.entity.CardsRetainKey;

@Component
@Mapper
public interface CardsRetainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	long countByExample(CardsRetainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int deleteByExample(CardsRetainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int deleteByPrimaryKey(CardsRetainKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int insert(CardsRetain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int insertSelective(CardsRetain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	List<CardsRetain> selectByExample(CardsRetainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	CardsRetain selectByPrimaryKey(CardsRetainKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int updateByExampleSelective(@Param("record") CardsRetain record, @Param("example") CardsRetainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int updateByExample(@Param("record") CardsRetain record, @Param("example") CardsRetainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int updateByPrimaryKeySelective(CardsRetain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cards_retain
	 * @mbg.generated  Thu Apr 09 11:15:08 JST 2020
	 */
	int updateByPrimaryKey(CardsRetain record);
}