package sp.co.soe.emp.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import sp.co.soe.emp.domain.entity.EmployeesM;
import sp.co.soe.emp.domain.entity.EmployeesMExample;

@Component
@Mapper
public interface EmployeesMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    long countByExample(EmployeesMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int deleteByExample(EmployeesMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int deleteByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int insert(EmployeesM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int insertSelective(EmployeesM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    List<EmployeesM> selectByExample(EmployeesMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    EmployeesM selectByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int updateByExampleSelective(@Param("record") EmployeesM record, @Param("example") EmployeesMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int updateByExample(@Param("record") EmployeesM record, @Param("example") EmployeesMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int updateByPrimaryKeySelective(EmployeesM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees_m
     *
     * @mbg.generated Mon Mar 30 00:37:11 JST 2020
     */
    int updateByPrimaryKey(EmployeesM record);
}