package sp.co.soe.emp.domain.repository;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import sp.co.soe.emp.domain.entity.EmployeeInfo;
import sp.co.soe.emp.domain.entity.EmployeeInfoExample;

import java.util.List;

@Component
@Mapper
public interface EmployeeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	long countByExample(EmployeeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int deleteByExample(EmployeeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int deleteByPrimaryKey(Integer manno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int insert(EmployeeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int insertSelective(EmployeeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	List<EmployeeInfo> selectByExample(EmployeeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	EmployeeInfo selectByPrimaryKey(Integer manno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int updateByExampleSelective(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int updateByExample(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int updateByPrimaryKeySelective(EmployeeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_info
	 * @mbg.generated  Tue Mar 24 22:41:21 JST 2020
	 */
	int updateByPrimaryKey(EmployeeInfo record);
}