package sp.co.soe.emp.domain.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sp.co.soe.emp.domain.entity.JobPosts;
import sp.co.soe.emp.domain.entity.JobPostsExample;

public interface JobPostsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	long countByExample(JobPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int deleteByExample(JobPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int deleteByPrimaryKey(String postCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int insert(JobPosts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int insertSelective(JobPosts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	List<JobPosts> selectByExample(JobPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	JobPosts selectByPrimaryKey(String postCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int updateByExampleSelective(@Param("record") JobPosts record, @Param("example") JobPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int updateByExample(@Param("record") JobPosts record, @Param("example") JobPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int updateByPrimaryKeySelective(JobPosts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job_posts
	 * @mbg.generated  Sat Apr 04 17:59:08 JST 2020
	 */
	int updateByPrimaryKey(JobPosts record);
}