package sp.co.soe.emp.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import sp.co.soe.emp.domain.entity.Menus;
import sp.co.soe.emp.domain.entity.MenusExample;

@Component
@Mapper
public interface MenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    long countByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    int deleteByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    int insert(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    int insertSelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    List<Menus> selectByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    int updateByExampleSelective(@Param("record") Menus record, @Param("example") MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Sat Apr 04 16:25:29 JST 2020
     */
    int updateByExample(@Param("record") Menus record, @Param("example") MenusExample example);
}