package sp.co.soe.emp.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import sp.co.soe.emp.domain.entity.UsersAccount;
import sp.co.soe.emp.domain.entity.UsersAccountExample;

@Component
@Mapper
public interface UsersAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	long countByExample(UsersAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int deleteByExample(UsersAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int deleteByPrimaryKey(String userName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int insert(UsersAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int insertSelective(UsersAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	List<UsersAccount> selectByExample(UsersAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	UsersAccount selectByPrimaryKey(String userName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int updateByExampleSelective(@Param("record") UsersAccount record, @Param("example") UsersAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int updateByExample(@Param("record") UsersAccount record, @Param("example") UsersAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int updateByPrimaryKeySelective(UsersAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_account
	 * @mbg.generated  Mon Mar 30 00:37:10 JST 2020
	 */
	int updateByPrimaryKey(UsersAccount record);

	int insertOrUpdate(UsersAccount record);
}